package view;

import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.DAO.CatalogoDAO;
import model.entity.Empleado;
import model.entity.Usuario;
import utilities.Constants.PanelMode;
import utilities.Constants.FormAction;
import utilities.DBConnection;
import utilities.Functions;

/**
 *
 * @author Ignacio Pineda Martín
 */
public class frmAppEmpleado extends javax.swing.JFrame {
    
    private Empleado empleado = null;
    private Usuario usuario = null;

    /**
     * Creates new form frmAppEmpleado
     */
    public frmAppEmpleado() {
        initComponents();
        // Título del formulario.
        this.setTitle("SoftBank - Empleado");
        // La posicionamos en el centro de la pantalla.
        this.setLocationRelativeTo(null);      
    }
    
    public frmAppEmpleado(Usuario usuario) {
        this();
        this.usuario = usuario;
        this.empleado = usuario.getEmpleado();
        setStatusBarText(String.format("Conectado %s %s",
                empleado.getNombreEmpleado(), empleado.getApellidosEmpleado()));
    }

    private void setStatusBarText(String texto) {
        Format f = new SimpleDateFormat("HH:mm:ss");
        txtStatus.setText(f.format(new Date()) + " " + texto);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlAppEmpleado = new javax.swing.JPanel();
        btnSucursalConsultas = new javax.swing.JButton();
        btnEmpleadoConsultas = new javax.swing.JButton();
        btnClienteConsultas = new javax.swing.JButton();
        btnCatalogoConsultas = new javax.swing.JButton();
        btnCuentasCorrientesMovimientosCRUD = new javax.swing.JButton();
        btnTarjetaCreditoMovimientoCRUD = new javax.swing.JButton();
        btnPrestamoMovimientoCRUD = new javax.swing.JButton();
        pnlStatusBar = new view.pnlAppSoftBank();
        txtStatus = new javax.swing.JLabel();
        mnbAppEmpleado = new javax.swing.JMenuBar();
        mnuDatosBasicos = new javax.swing.JMenu();
        mnuSucursal = new javax.swing.JMenu();
        mniSucursalConsultas = new javax.swing.JMenuItem();
        mniSucursalCRUD = new javax.swing.JMenuItem();
        mnuEmpleado = new javax.swing.JMenu();
        mniEmpleadoConsultas = new javax.swing.JMenuItem();
        mniEmpleadoCRUD = new javax.swing.JMenuItem();
        mnuCliente = new javax.swing.JMenu();
        mniClienteConsultas = new javax.swing.JMenuItem();
        mniClienteCRUD = new javax.swing.JMenuItem();
        mnuCatalogo = new javax.swing.JMenu();
        mniCatalogoConsultas = new javax.swing.JMenuItem();
        mniCatalogoCRUD = new javax.swing.JMenuItem();
        mnuCuentasCorrientes = new javax.swing.JMenu();
        mniCuentasCorrientesMovimientosCRUD = new javax.swing.JMenuItem();
        mniCuentasCorrientesAlta = new javax.swing.JMenuItem();
        mniCuentasCorrientesModificación = new javax.swing.JMenuItem();
        mniCuentasCorrientesCancelación = new javax.swing.JMenuItem();
        mnuTarjetaCredito = new javax.swing.JMenu();
        mniTarjetaCreditoMovimientoCRUD = new javax.swing.JMenuItem();
        mniTarjetaCreditoAlta = new javax.swing.JMenuItem();
        mniTarjetaCreditoModificación = new javax.swing.JMenuItem();
        mniTarjetaCreditoCancelación = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniTarjetaCreditoLiquidacion = new javax.swing.JMenuItem();
        mnuPrestamo = new javax.swing.JMenu();
        mniPrestamoMovimientoCRUD = new javax.swing.JMenuItem();
        mniPrestamoAlta = new javax.swing.JMenuItem();
        mniPrestamoModificación = new javax.swing.JMenuItem();
        mniPrestamoCancelación = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniPrestamoLiquidacion = new javax.swing.JMenuItem();
        mnuAplicacion = new javax.swing.JMenu();
        mniAplicacionCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(new ImageIcon(Functions.getImage("icons/SoftBank 16px.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        java.awt.GridBagLayout pnlAppEmpleadoLayout = new java.awt.GridBagLayout();
        pnlAppEmpleadoLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        pnlAppEmpleadoLayout.rowHeights = new int[] {0, 5, 0, 5, 0};
        pnlAppEmpleado.setLayout(pnlAppEmpleadoLayout);

        btnSucursalConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sucursal 128px.png"))); // NOI18N
        btnSucursalConsultas.setToolTipText("Sucursal: Consultas");
        btnSucursalConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalConsultasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlAppEmpleado.add(btnSucursalConsultas, gridBagConstraints);

        btnEmpleadoConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/empleado 128px.png"))); // NOI18N
        btnEmpleadoConsultas.setToolTipText("Empleado: Consultas");
        btnEmpleadoConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoConsultasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        pnlAppEmpleado.add(btnEmpleadoConsultas, gridBagConstraints);

        btnClienteConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cliente 128px.png"))); // NOI18N
        btnClienteConsultas.setToolTipText("Cliente: Consultas");
        btnClienteConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteConsultasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        pnlAppEmpleado.add(btnClienteConsultas, gridBagConstraints);

        btnCatalogoConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/catalogo 128px.png"))); // NOI18N
        btnCatalogoConsultas.setToolTipText("Catálogo: Consultas");
        btnCatalogoConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoConsultasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        pnlAppEmpleado.add(btnCatalogoConsultas, gridBagConstraints);

        btnCuentasCorrientesMovimientosCRUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cuenta-corriente 128px.png"))); // NOI18N
        btnCuentasCorrientesMovimientosCRUD.setToolTipText("Cuentas Corrientes: alta, baja y modificación de movimientos");
        btnCuentasCorrientesMovimientosCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentasCorrientesMovimientosCRUDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pnlAppEmpleado.add(btnCuentasCorrientesMovimientosCRUD, gridBagConstraints);

        btnTarjetaCreditoMovimientoCRUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tarjeta-credito 128px.png"))); // NOI18N
        btnTarjetaCreditoMovimientoCRUD.setToolTipText("Tarjetas de Crédito: alta, baja y modificación de movimientos");
        btnTarjetaCreditoMovimientoCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaCreditoMovimientoCRUDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        pnlAppEmpleado.add(btnTarjetaCreditoMovimientoCRUD, gridBagConstraints);

        btnPrestamoMovimientoCRUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/prestamo 128px.png"))); // NOI18N
        btnPrestamoMovimientoCRUD.setToolTipText("Préstamos: alta, baja y modificación de movimientos");
        btnPrestamoMovimientoCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoMovimientoCRUDActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        pnlAppEmpleado.add(btnPrestamoMovimientoCRUD, gridBagConstraints);

        getContentPane().add(pnlAppEmpleado);

        pnlStatusBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlStatusBar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlStatusBar.setMinimumSize(new java.awt.Dimension(131, 100));
        pnlStatusBar.setName("pnlStatusBar"); // NOI18N
        pnlStatusBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStatus.setText(" ");
        pnlStatusBar.add(txtStatus);

        getContentPane().add(pnlStatusBar);

        mnuDatosBasicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/datos-maestros 16px.png"))); // NOI18N
        mnuDatosBasicos.setText("Datos básicos");

        mnuSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sucursal 16px.png"))); // NOI18N
        mnuSucursal.setText("Sucursal");

        mniSucursalConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sucursal 16px.png"))); // NOI18N
        mniSucursalConsultas.setText("Consultas");
        mniSucursalConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSucursalConsultasActionPerformed(evt);
            }
        });
        mnuSucursal.add(mniSucursalConsultas);

        mniSucursalCRUD.setText("Altas, bajas y modificaciones");
        mniSucursalCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSucursalCRUDActionPerformed(evt);
            }
        });
        mnuSucursal.add(mniSucursalCRUD);

        mnuDatosBasicos.add(mnuSucursal);

        mnuEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/empleado 16px.png"))); // NOI18N
        mnuEmpleado.setText("Empleado");

        mniEmpleadoConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/empleado 16px.png"))); // NOI18N
        mniEmpleadoConsultas.setText("Consultas");
        mniEmpleadoConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmpleadoConsultasActionPerformed(evt);
            }
        });
        mnuEmpleado.add(mniEmpleadoConsultas);

        mniEmpleadoCRUD.setText("Altas, bajas y modificaciones");
        mniEmpleadoCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniEmpleadoCRUDActionPerformed(evt);
            }
        });
        mnuEmpleado.add(mniEmpleadoCRUD);

        mnuDatosBasicos.add(mnuEmpleado);

        mnuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cliente 16px.png"))); // NOI18N
        mnuCliente.setText("Cliente");

        mniClienteConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cliente 16px.png"))); // NOI18N
        mniClienteConsultas.setText("Consultas");
        mniClienteConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClienteConsultasActionPerformed(evt);
            }
        });
        mnuCliente.add(mniClienteConsultas);

        mniClienteCRUD.setText("Altas, bajas y modificaciones");
        mniClienteCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClienteCRUDActionPerformed(evt);
            }
        });
        mnuCliente.add(mniClienteCRUD);

        mnuDatosBasicos.add(mnuCliente);

        mnuCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/catalogo 16px.png"))); // NOI18N
        mnuCatalogo.setText("Catálogo");

        mniCatalogoConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/catalogo 16px.png"))); // NOI18N
        mniCatalogoConsultas.setText("Consultas");
        mniCatalogoConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCatalogoConsultasActionPerformed(evt);
            }
        });
        mnuCatalogo.add(mniCatalogoConsultas);

        mniCatalogoCRUD.setText("Altas, bajas y modificaciones");
        mniCatalogoCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCatalogoCRUDActionPerformed(evt);
            }
        });
        mnuCatalogo.add(mniCatalogoCRUD);

        mnuDatosBasicos.add(mnuCatalogo);

        mnbAppEmpleado.add(mnuDatosBasicos);

        mnuCuentasCorrientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cuenta-corriente 16px.png"))); // NOI18N
        mnuCuentasCorrientes.setText("Cuentas Corrientes");

        mniCuentasCorrientesMovimientosCRUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cuenta-corriente 16px.png"))); // NOI18N
        mniCuentasCorrientesMovimientosCRUD.setText("Alta, baja y modificación de movimientos");
        mniCuentasCorrientesMovimientosCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCuentasCorrientesMovimientosCRUDActionPerformed(evt);
            }
        });
        mnuCuentasCorrientes.add(mniCuentasCorrientesMovimientosCRUD);

        mniCuentasCorrientesAlta.setText("Alta de nueva cuenta");
        mniCuentasCorrientesAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCuentasCorrientesAltaActionPerformed(evt);
            }
        });
        mnuCuentasCorrientes.add(mniCuentasCorrientesAlta);

        mniCuentasCorrientesModificación.setText("Modificación tipo interés");
        mniCuentasCorrientesModificación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCuentasCorrientesModificaciónActionPerformed(evt);
            }
        });
        mnuCuentasCorrientes.add(mniCuentasCorrientesModificación);

        mniCuentasCorrientesCancelación.setText("Cancelación de cuenta");
        mniCuentasCorrientesCancelación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCuentasCorrientesCancelaciónActionPerformed(evt);
            }
        });
        mnuCuentasCorrientes.add(mniCuentasCorrientesCancelación);

        mnbAppEmpleado.add(mnuCuentasCorrientes);

        mnuTarjetaCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tarjeta-credito 16px.png"))); // NOI18N
        mnuTarjetaCredito.setText("Tarjetas de Crédito");

        mniTarjetaCreditoMovimientoCRUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tarjeta-credito 16px.png"))); // NOI18N
        mniTarjetaCreditoMovimientoCRUD.setText("Alta, baja y modificación de movimientos");
        mniTarjetaCreditoMovimientoCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTarjetaCreditoMovimientoCRUDActionPerformed(evt);
            }
        });
        mnuTarjetaCredito.add(mniTarjetaCreditoMovimientoCRUD);

        mniTarjetaCreditoAlta.setText("Alta de nueva tarjeta");
        mniTarjetaCreditoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTarjetaCreditoAltaActionPerformed(evt);
            }
        });
        mnuTarjetaCredito.add(mniTarjetaCreditoAlta);

        mniTarjetaCreditoModificación.setText("Modificación de tarjeta");
        mniTarjetaCreditoModificación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTarjetaCreditoModificaciónActionPerformed(evt);
            }
        });
        mnuTarjetaCredito.add(mniTarjetaCreditoModificación);

        mniTarjetaCreditoCancelación.setText("Cancelación de tarjeta");
        mniTarjetaCreditoCancelación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTarjetaCreditoCancelaciónActionPerformed(evt);
            }
        });
        mnuTarjetaCredito.add(mniTarjetaCreditoCancelación);

        jSeparator1.setToolTipText("Procesos de back-end");
        mnuTarjetaCredito.add(jSeparator1);

        mniTarjetaCreditoLiquidacion.setText("Liquidación de tarjetas");
        mniTarjetaCreditoLiquidacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTarjetaCreditoLiquidacionActionPerformed(evt);
            }
        });
        mnuTarjetaCredito.add(mniTarjetaCreditoLiquidacion);

        mnbAppEmpleado.add(mnuTarjetaCredito);

        mnuPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/prestamo 16px.png"))); // NOI18N
        mnuPrestamo.setText("Préstamos");

        mniPrestamoMovimientoCRUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/prestamo 16px.png"))); // NOI18N
        mniPrestamoMovimientoCRUD.setText("Alta, baja y modificación de movimientos");
        mniPrestamoMovimientoCRUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPrestamoMovimientoCRUDActionPerformed(evt);
            }
        });
        mnuPrestamo.add(mniPrestamoMovimientoCRUD);

        mniPrestamoAlta.setText("Alta de nuevo préstamo");
        mniPrestamoAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPrestamoAltaActionPerformed(evt);
            }
        });
        mnuPrestamo.add(mniPrestamoAlta);

        mniPrestamoModificación.setText("Modificación de préstamo");
        mniPrestamoModificación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPrestamoModificaciónActionPerformed(evt);
            }
        });
        mnuPrestamo.add(mniPrestamoModificación);

        mniPrestamoCancelación.setText("Cancelación de préstamo");
        mniPrestamoCancelación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPrestamoCancelaciónActionPerformed(evt);
            }
        });
        mnuPrestamo.add(mniPrestamoCancelación);

        jSeparator2.setToolTipText("Procesos de back-end");
        mnuPrestamo.add(jSeparator2);

        mniPrestamoLiquidacion.setText("Liquidación de préstamos");
        mniPrestamoLiquidacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPrestamoLiquidacionActionPerformed(evt);
            }
        });
        mnuPrestamo.add(mniPrestamoLiquidacion);

        mnbAppEmpleado.add(mnuPrestamo);

        mnuAplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SoftBank 16px.png"))); // NOI18N
        mnuAplicacion.setText("Aplicación");

        mniAplicacionCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mniAplicacionCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit 16px.png"))); // NOI18N
        mniAplicacionCerrarSesion.setText("Cerrar sesión");
        mniAplicacionCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAplicacionCerrarSesionActionPerformed(evt);
            }
        });
        mnuAplicacion.add(mniAplicacionCerrarSesion);

        mnbAppEmpleado.add(mnuAplicacion);

        setJMenuBar(mnbAppEmpleado);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        mniAplicacionCerrarSesion.doClick();
    }//GEN-LAST:event_formWindowClosing

    private void mniAplicacionCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAplicacionCerrarSesionActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this,
                                                   "¿Desea cerrar la sesión?",
                                                   this.getTitle(),
                                                   JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            // Cerramos el formulario de "Persona" y volvemos al formulario de
            // "Login".
            frmLogin fl = new frmLogin();
            fl.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_mniAplicacionCerrarSesionActionPerformed

    private void mniSucursalConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSucursalConsultasActionPerformed
        // Cremos el formulario.
        frmSucursal fs = new frmSucursal();
        // Modo "Consulta"        
        fs.setFormMode(PanelMode.SELECTION);
        // Hacemos visible el formulario.
        fs.setVisible(true);
    }//GEN-LAST:event_mniSucursalConsultasActionPerformed

    private void btnSucursalConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalConsultasActionPerformed
        mniSucursalConsultas.doClick();
    }//GEN-LAST:event_btnSucursalConsultasActionPerformed

    private void mniSucursalCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSucursalCRUDActionPerformed
        // Cremos el formulario.
        frmSucursal fs = new frmSucursal();
        // Modo "CRUD" (al ser modo por defecto, no haría falta indicarlo).
        fs.setFormMode(PanelMode.CRUD);
        // Hacemos visible el formulario.
        fs.setVisible(true);
    }//GEN-LAST:event_mniSucursalCRUDActionPerformed

    private void mniEmpleadoConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmpleadoConsultasActionPerformed
        // Cremos el formulario.
        frmEmpleado fe = new frmEmpleado();
        // Modo "Consulta"        
        fe.setFormMode(PanelMode.SELECTION);
        // Hacemos visible el formulario.
        fe.setVisible(true);
    }//GEN-LAST:event_mniEmpleadoConsultasActionPerformed

    private void mniEmpleadoCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniEmpleadoCRUDActionPerformed
        // Cremos el formulario.
        frmEmpleado fe = new frmEmpleado();
        // Modo "CRUD" (al ser modo por defecto, no haría falta indicarlo).
        fe.setFormMode(PanelMode.CRUD);
        // Hacemos visible el formulario.
        fe.setVisible(true);
    }//GEN-LAST:event_mniEmpleadoCRUDActionPerformed

    private void btnEmpleadoConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoConsultasActionPerformed
        mniEmpleadoConsultas.doClick();
    }//GEN-LAST:event_btnEmpleadoConsultasActionPerformed

    private void btnClienteConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteConsultasActionPerformed
        mniClienteConsultas.doClick();
    }//GEN-LAST:event_btnClienteConsultasActionPerformed

    private void mniClienteConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClienteConsultasActionPerformed
        // Creamos el formulario.
        frmCliente fc = new frmCliente();
        // Pasamos el usuario.
        fc.setAppUser(usuario);
        // Modo "Consulta"
        fc.setFormMode(PanelMode.SELECTION);
        // Hacemos visible el formulario.
        fc.setVisible(true);
    }//GEN-LAST:event_mniClienteConsultasActionPerformed

    private void mniClienteCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClienteCRUDActionPerformed
        // Creamos el formulario.
        frmCliente fc = new frmCliente();
        // Pasamos el usuario.
        fc.setAppUser(usuario);        
        // Modo "CRUD" (al ser modo por defecto, no haría falta indicarlo).
        fc.setFormMode(PanelMode.CRUD);
        // Hacemos visible el formulario.
        fc.setVisible(true);
    }//GEN-LAST:event_mniClienteCRUDActionPerformed

    private void mniCatalogoConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCatalogoConsultasActionPerformed
        // Creamos el formulario.
        frmCatalogo fc = new frmCatalogo();
        // Modo "Consulta"
        fc.setFormMode(PanelMode.SELECTION);
        // Hacemos visible el formulario.
        fc.setVisible(true);
    }//GEN-LAST:event_mniCatalogoConsultasActionPerformed

    private void mniCatalogoCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCatalogoCRUDActionPerformed
        // Creamos el formulario.
        frmCatalogo fc = new frmCatalogo();
        // Modo "CRUD" (al ser modo por defecto, no haría falta indicarlo).
        fc.setFormMode(PanelMode.CRUD);
        // Hacemos visible el formulario.
        fc.setVisible(true);
    }//GEN-LAST:event_mniCatalogoCRUDActionPerformed

    private void btnCatalogoConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoConsultasActionPerformed
        mniCatalogoConsultas.doClick();
    }//GEN-LAST:event_btnCatalogoConsultasActionPerformed

    private void btnCuentasCorrientesMovimientosCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentasCorrientesMovimientosCRUDActionPerformed
        mniCuentasCorrientesMovimientosCRUD.doClick();
    }//GEN-LAST:event_btnCuentasCorrientesMovimientosCRUDActionPerformed

    private void mniCuentasCorrientesMovimientosCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCuentasCorrientesMovimientosCRUDActionPerformed
        // Creamos el formulario.
        frmCuentaCorriente fcc = new frmCuentaCorriente();
        // Pasamos el usuario.
        fcc.setAppUser(usuario);
         // Modo "SELECTION" + "MOVEMENT" (Alta, baja y modificación de movimientos)
        fcc.setFormModeAndAction(PanelMode.SELECTION, FormAction.MOVEMENT);
        // Hacemos visible el formulario.
        fcc.setVisible(true);       
    }//GEN-LAST:event_mniCuentasCorrientesMovimientosCRUDActionPerformed

    private void mniCuentasCorrientesAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCuentasCorrientesAltaActionPerformed
        // Creamos el formulario.
        frmCuentaCorriente fcc = new frmCuentaCorriente();
        // Pasamos el usuario.
        fcc.setAppUser(usuario);        
        // Modo "CRUD" + "NEW" (Alta de cuenta. Modo por defecto.)
        fcc.setFormModeAndAction(PanelMode.CRUD, FormAction.NEW);
        // Hacemos visible el formulario.
        fcc.setVisible(true);  
    }//GEN-LAST:event_mniCuentasCorrientesAltaActionPerformed

    private void mniCuentasCorrientesModificaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCuentasCorrientesModificaciónActionPerformed
        // Creamos el formulario.
        frmCuentaCorriente fcc = new frmCuentaCorriente();
        // Pasamos el usuario.
        fcc.setAppUser(usuario);        
        // Modo "SELECTION" + "MODIFY" (Modificación de cuenta)
        fcc.setFormModeAndAction(PanelMode.SELECTION, FormAction.MODIFY);
        // Hacemos visible el formulario.
        fcc.setVisible(true);  
    }//GEN-LAST:event_mniCuentasCorrientesModificaciónActionPerformed

    private void mniCuentasCorrientesCancelaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCuentasCorrientesCancelaciónActionPerformed
        // Creamos el formulario.
        frmCuentaCorriente fcc = new frmCuentaCorriente();
        // Pasamos el usuario.
        fcc.setAppUser(usuario);        
        // Modo "SELECTION" + "CANCEL" (Cancelación de cuenta)
        fcc.setFormModeAndAction(PanelMode.SELECTION, FormAction.CANCEL);
        // Hacemos visible el formulario.
        fcc.setVisible(true);
    }//GEN-LAST:event_mniCuentasCorrientesCancelaciónActionPerformed

    private void btnTarjetaCreditoMovimientoCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaCreditoMovimientoCRUDActionPerformed
        mniTarjetaCreditoMovimientoCRUD.doClick();
    }//GEN-LAST:event_btnTarjetaCreditoMovimientoCRUDActionPerformed

    private void mniTarjetaCreditoMovimientoCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTarjetaCreditoMovimientoCRUDActionPerformed
        // Creamos el formulario.
        frmTarjetaCredito ftc = new frmTarjetaCredito();
        // Pasamos el usuario.
        ftc.setAppUser(usuario);
         // Modo "SELECTION" + "MOVEMENT" (Alta, baja y modificación de movimientos)
        ftc.setFormModeAndAction(PanelMode.SELECTION, FormAction.MOVEMENT);
        // Hacemos visible el formulario.
        ftc.setVisible(true);  
    }//GEN-LAST:event_mniTarjetaCreditoMovimientoCRUDActionPerformed

    private void mniTarjetaCreditoAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTarjetaCreditoAltaActionPerformed
        // Creamos el formulario.
        frmTarjetaCredito ftc = new frmTarjetaCredito();
        // Pasamos el usuario.
        ftc.setAppUser(usuario);        
        // Modo "CRUD" + "NEW" (Alta de tarjeta. Modo por defecto.)
        ftc.setFormModeAndAction(PanelMode.CRUD, FormAction.NEW);
        // Hacemos visible el formulario.
        ftc.setVisible(true);  
    }//GEN-LAST:event_mniTarjetaCreditoAltaActionPerformed

    private void mniTarjetaCreditoModificaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTarjetaCreditoModificaciónActionPerformed
        // Creamos el formulario.
        frmTarjetaCredito ftc = new frmTarjetaCredito();
        // Pasamos el usuario.
        ftc.setAppUser(usuario);        
        // Modo "SELECTION" + "MODIFY" (Modificación de tarjeta)
        ftc.setFormModeAndAction(PanelMode.SELECTION, FormAction.MODIFY);
        // Hacemos visible el formulario.
        ftc.setVisible(true);  
    }//GEN-LAST:event_mniTarjetaCreditoModificaciónActionPerformed

    private void mniTarjetaCreditoCancelaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTarjetaCreditoCancelaciónActionPerformed
        // Creamos el formulario.
        frmTarjetaCredito ftc = new frmTarjetaCredito();
        // Pasamos el usuario.
        ftc.setAppUser(usuario);        
        // Modo "SELECTION" + "CANCEL" (Cancelación de tarjeta)
        ftc.setFormModeAndAction(PanelMode.SELECTION, FormAction.CANCEL);
        // Hacemos visible el formulario.
        ftc.setVisible(true); 
    }//GEN-LAST:event_mniTarjetaCreditoCancelaciónActionPerformed

    private void mniTarjetaCreditoLiquidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTarjetaCreditoLiquidacionActionPerformed
        // Liquidación de Tarjetas de Crédito.
        CatalogoDAO cdao = new CatalogoDAO(new DBConnection().getEntityManagerFactory());
        frmLiquidacion fl = new frmLiquidacion(cdao.getTarjetaCredito());
        fl.setVisible(true);
    }//GEN-LAST:event_mniTarjetaCreditoLiquidacionActionPerformed

    private void btnPrestamoMovimientoCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoMovimientoCRUDActionPerformed
        mniPrestamoMovimientoCRUD.doClick();
    }//GEN-LAST:event_btnPrestamoMovimientoCRUDActionPerformed

    private void mniPrestamoMovimientoCRUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPrestamoMovimientoCRUDActionPerformed
        // Creamos el formulario.
        frmPrestamo fp = new frmPrestamo();
        // Pasamos el usuario.
        fp.setAppUser(usuario);
         // Modo "SELECTION" + "MOVEMENT" (Alta, baja y modificación de movimientos)
        fp.setFormModeAndAction(PanelMode.SELECTION, FormAction.MOVEMENT);
        // Hacemos visible el formulario.
        fp.setVisible(true); 
    }//GEN-LAST:event_mniPrestamoMovimientoCRUDActionPerformed

    private void mniPrestamoAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPrestamoAltaActionPerformed
        // Creamos el formulario.
        frmPrestamo fp = new frmPrestamo();
        // Pasamos el usuario.
        fp.setAppUser(usuario);
        // Modo "CRUD" + "NEW" (Alta de préstamo. Modo por defecto.)
        fp.setFormModeAndAction(PanelMode.CRUD, FormAction.NEW);
        // Hacemos visible el formulario.
        fp.setVisible(true);
    }//GEN-LAST:event_mniPrestamoAltaActionPerformed

    private void mniPrestamoModificaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPrestamoModificaciónActionPerformed
        // Creamos el formulario.
        frmPrestamo fp = new frmPrestamo();
        // Pasamos el usuario.
        fp.setAppUser(usuario);
        // Modo "SELECTION" + "MODIFY" (Modificación de préstamo)
        fp.setFormModeAndAction(PanelMode.SELECTION, FormAction.MODIFY);
        // Hacemos visible el formulario.
        fp.setVisible(true);
    }//GEN-LAST:event_mniPrestamoModificaciónActionPerformed

    private void mniPrestamoCancelaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPrestamoCancelaciónActionPerformed
        // Creamos el formulario.
        frmPrestamo fp = new frmPrestamo();
        // Pasamos el usuario.
        fp.setAppUser(usuario);
        // Modo "SELECTION" + "CANCEL" (Cancelación de préstamo)
        fp.setFormModeAndAction(PanelMode.SELECTION, FormAction.CANCEL);
        // Hacemos visible el formulario.
        fp.setVisible(true);
    }//GEN-LAST:event_mniPrestamoCancelaciónActionPerformed

    private void mniPrestamoLiquidacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPrestamoLiquidacionActionPerformed
        // Liquidación de Préstamos.
        CatalogoDAO cdao = new CatalogoDAO(new DBConnection().getEntityManagerFactory());
        frmLiquidacion fl = new frmLiquidacion(cdao.getPrestamo());
        fl.setVisible(true);
    }//GEN-LAST:event_mniPrestamoLiquidacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAppEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAppEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAppEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAppEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAppEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalogoConsultas;
    private javax.swing.JButton btnClienteConsultas;
    private javax.swing.JButton btnCuentasCorrientesMovimientosCRUD;
    private javax.swing.JButton btnEmpleadoConsultas;
    private javax.swing.JButton btnPrestamoMovimientoCRUD;
    private javax.swing.JButton btnSucursalConsultas;
    private javax.swing.JButton btnTarjetaCreditoMovimientoCRUD;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar mnbAppEmpleado;
    private javax.swing.JMenuItem mniAplicacionCerrarSesion;
    private javax.swing.JMenuItem mniCatalogoCRUD;
    private javax.swing.JMenuItem mniCatalogoConsultas;
    private javax.swing.JMenuItem mniClienteCRUD;
    private javax.swing.JMenuItem mniClienteConsultas;
    private javax.swing.JMenuItem mniCuentasCorrientesAlta;
    private javax.swing.JMenuItem mniCuentasCorrientesCancelación;
    private javax.swing.JMenuItem mniCuentasCorrientesModificación;
    private javax.swing.JMenuItem mniCuentasCorrientesMovimientosCRUD;
    private javax.swing.JMenuItem mniEmpleadoCRUD;
    private javax.swing.JMenuItem mniEmpleadoConsultas;
    private javax.swing.JMenuItem mniPrestamoAlta;
    private javax.swing.JMenuItem mniPrestamoCancelación;
    private javax.swing.JMenuItem mniPrestamoLiquidacion;
    private javax.swing.JMenuItem mniPrestamoModificación;
    private javax.swing.JMenuItem mniPrestamoMovimientoCRUD;
    private javax.swing.JMenuItem mniSucursalCRUD;
    private javax.swing.JMenuItem mniSucursalConsultas;
    private javax.swing.JMenuItem mniTarjetaCreditoAlta;
    private javax.swing.JMenuItem mniTarjetaCreditoCancelación;
    private javax.swing.JMenuItem mniTarjetaCreditoLiquidacion;
    private javax.swing.JMenuItem mniTarjetaCreditoModificación;
    private javax.swing.JMenuItem mniTarjetaCreditoMovimientoCRUD;
    private javax.swing.JMenu mnuAplicacion;
    private javax.swing.JMenu mnuCatalogo;
    private javax.swing.JMenu mnuCliente;
    private javax.swing.JMenu mnuCuentasCorrientes;
    private javax.swing.JMenu mnuDatosBasicos;
    private javax.swing.JMenu mnuEmpleado;
    private javax.swing.JMenu mnuPrestamo;
    private javax.swing.JMenu mnuSucursal;
    private javax.swing.JMenu mnuTarjetaCredito;
    private javax.swing.JPanel pnlAppEmpleado;
    private javax.swing.JPanel pnlStatusBar;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
}
