package view;

//<editor-fold defaultstate="collapsed" desc=" Librerías importadas... ">
import java.awt.Component;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.EntityManagerFactory;
import model.entity.Usuario;

import utilities.Constants.FormAction;
import utilities.Constants.PanelMode;
import utilities.DBConnection;
import utilities.Functions;
//</editor-fold>

/**
 * Formulario base para la aplicación. Contiene tanto las propiedades como
 * los comportamientos básicos de los formularios creados en la aplicación.
 * 
 * @author Ignacio Pineda Martín
 */
public class frmAppSoftBank extends javax.swing.JFrame {

    private Usuario appUser;
    protected PanelMode formMode;
    protected FormAction formAction;    
    protected Object jpaObject;
    protected EntityManagerFactory emf;
    
    /**
     * Creates new form frmAppSoftBank
     */
    public frmAppSoftBank() {
        // initComponents();
        // Creamos el EntityManagerFactory.
        emf = new DBConnection().getEntityManagerFactory();
        // Limpiamos la caché para refrescar los objetos JPA.
        emf.getCache().evictAll();
    }
    
    public void inicializarComponentes() {
        initComponents();
        setFormMode(PanelMode.CRUD);
        setFormAction(FormAction.NEW);
    }
    
    
    public void setAppUser(Usuario appUser) {
        this.appUser = appUser;
    }
            
    public Usuario getAppUser() {
        return this.appUser;
    }
    
    public void setFormMode(PanelMode formMode) {
        this.formMode = formMode;
        switch (this.formMode) {
            case CRUD:
                disableCRUDButtons();
                break;
            case SELECTION:
                this.setTitle(this.getTitle() + " (Consulta)");               
                ((pnlAppSoftBank) pnlBotones).setPanelMode(PanelMode.SELECTION);
                ((pnlAppSoftBank) pnlStatusBar).setPanelMode(PanelMode.READ_ONLY);                
                break;
            case READ_ONLY:
                this.setTitle(this.getTitle() + " (Visualización)");
                ((pnlAppSoftBank) pnlBotones).setPanelMode(PanelMode.READ_ONLY);
                ((pnlAppSoftBank) pnlStatusBar).setPanelMode(PanelMode.READ_ONLY);
                break;
            default:
                throw new AssertionError();
        }        
    }
    
    public PanelMode getFormMode() {
        return this.formMode;
    }    

    public void setFormAction(FormAction formAction) {
        this.formAction = formAction;
        switch (this.formAction) {
            case NEW:
                
                break;
            case CANCEL:
             
                break;
            case MODIFY:

                break;
            case QUERY:

                break;                
            default:
                throw new AssertionError();
        }        
    }
    
    public FormAction getFormAction() {
        return this.formAction;
    } 
    
    public void setJPAObject(Object jpaObject) {
        this.jpaObject = jpaObject;
    }
    
    public void setStatusBarText(String texto) {
        Format f = new SimpleDateFormat("HH:mm:ss");
        txtStatus.setText(f.format(new Date()) + " " + texto);
    }
    
    protected void enableCRUDButtons() {
        if (formMode == PanelMode.CRUD) {
            btnInsertar.setEnabled(true);
            btnModificar.setEnabled(true);
            btnEliminar.setEnabled(true);
        }
    }

    protected void disableCRUDButtons() {
        if (formMode == PanelMode.CRUD) {
            btnInsertar.setEnabled(false);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
        }
    }
    
    protected void tryEnableCRUDButtons() {
        enableCRUDButtons();
        for (Component c : Functions.getComponents(this)) {
            if (c instanceof pnlAppSoftBank pasb) {
                if (!pasb.checkRequiredFields()) {
                    disableCRUDButtons();
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotones = new view.pnlAppSoftBank();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        pnlStatusBar = new view.pnlAppSoftBank();
        txtStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        pnlBotones.setName("pnlBotones"); // NOI18N
        pnlBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        btnInsertar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/insert 16px.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.setAlignmentY(0.0F);
        btnInsertar.setName("btnInsertar"); // NOI18N
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnInsertar);

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/modify 16px.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setAlignmentY(0.0F);
        btnModificar.setName("btnModificar"); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnModificar);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete 16px.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setAlignmentY(0.0F);
        btnEliminar.setName("btnEliminar"); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnEliminar);

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clean 16px.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setAlignmentY(0.0F);
        btnLimpiar.setName("btnLimpiar"); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnLimpiar);

        getContentPane().add(pnlBotones);

        pnlStatusBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlStatusBar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlStatusBar.setMinimumSize(new java.awt.Dimension(131, 100));
        pnlStatusBar.setName("pnlStatusBar"); // NOI18N
        pnlStatusBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStatus.setText(" ");
        pnlStatusBar.add(txtStatus);

        getContentPane().add(pnlStatusBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // Implementado en clases inferiores.
    }//GEN-LAST:event_btnModificarActionPerformed

    protected void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Implementado en clases inferiores.
    }//GEN-LAST:event_btnEliminarActionPerformed

    protected void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Limpiamos el mensaje de estado en la barra de estado.
        txtStatus.setText(" ");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    protected void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // Implementado en clases inferiores.
    }//GEN-LAST:event_btnInsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAppSoftBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAppSoftBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAppSoftBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAppSoftBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAppSoftBank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnEliminar;
    protected javax.swing.JButton btnInsertar;
    protected javax.swing.JButton btnLimpiar;
    protected javax.swing.JButton btnModificar;
    protected javax.swing.JPanel pnlBotones;
    protected javax.swing.JPanel pnlStatusBar;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
}
