import javax.persistence.EntityManagerFactory;
import model.DAO.ClienteDAO;
import model.entity.Cliente;
import utilities.DBConnection;
import utilities.Item;

/**
 * Prueba para almacenar objetos completos en un ComboBox y luego recuperar
 * su información.
 * <pre>{@code
 * JComboBox<Item<Car>> comboBox = new JComboBox<Item<Car>>();
 * // Añadir objetos al ComboBox.
 * Car c1 = new Car("Ford", "Crown Victoria");
 * Car c2 = new Car("Ford", "Focus");
 * comboBox.addItem( new Item<Car>(c1, c1.getModel()) );
 * comboBox.addItem( new Item<Car>(c2, c2.getModel()) );
 * // Recuperar objetos almacenados en el ComboBox.
 * Item item = (Item)comboBox.getSelectedItem();
 * Car car = (Car)item.getValue();
 * }
 * </pre>
 *
 * @see
 * <a href="https://tips4java.wordpress.com/2013/02/18/combo-box-with-hidden-data/">
 * "ComboBox con datos ocultos"</a>
 * @author Ignacio Pineda Martín
 */
public class ComboBoxObjetosTest extends javax.swing.JFrame {

    /**
     * Creates new form ComboBoxObjetosTest
     */
    public ComboBoxObjetosTest() {
        initComponents();
        rellenarComboBox();
    }

    private void rellenarComboBox() {
        EntityManagerFactory emf = new DBConnection().getEntityManagerFactory();
        ClienteDAO sdao = new ClienteDAO(emf);
        
        for (Cliente c : sdao.buscarCliente("")) {
            cbxCliente.addItem( new Item<Cliente>(c, c.getClaveIdentificacion()) );
        }
        cbxCliente.setSelectedIndex(-1);
        lblNombre.setText("");                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxCliente = new javax.swing.JComboBox<Item<Cliente>>();
        lblNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbxCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxClienteItemStateChanged(evt);
            }
        });
        cbxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxCliente, 0, 309, Short.MAX_VALUE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClienteActionPerformed

    }//GEN-LAST:event_cbxClienteActionPerformed

    private void cbxClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxClienteItemStateChanged
        if (cbxCliente.getSelectedIndex() != -1) {
            Item item = (Item) cbxCliente.getSelectedItem();
            Cliente c = (Cliente) item.getValue();
            lblNombre.setText(c.getNombreCliente() + " " + c.getApellidosCliente());
        }
    }//GEN-LAST:event_cbxClienteItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboBoxObjetosTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboBoxObjetosTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboBoxObjetosTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBoxObjetosTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboBoxObjetosTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Item<Cliente>> cbxCliente;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
