--
-- Consulta de todos los productos de todos los clientes.
--
SELECT C.NOMBRE_CLIENTE, C.APELLIDOS_CLIENTE, 
       CAT.NOMBRE_PRODUCTO, PB.FEC_APERTURA, 
       S.COD_SUCURSAL, S.NOMBRE_SUCURSAL AS "N.SUC.", 
       PB.ID_PRODUCTO_BANCARIO AS "ID_PB",
       CC.ID_CUENTA_CORRIENTE AS "ID_CC", CC.IBAN,
       TC.ID_TARJETA_CREDITO AS "ID_TC", TC.NUMERO_TARJETA,
       P.NUMERO_PRESTAMO, P.IMP_CONCEDIDO,
       A.ID_AVAL, A.NUMERO_AVAL
FROM CLIENTE C, CLIENTE_PRODUCTO_BANCARIO CPB,
     CATALOGO CAT,
     SUCURSAL S,
     PRODUCTO_BANCARIO PB
     LEFT OUTER JOIN CUENTA_CORRIENTE CC
        ON CC.ID_PRODUCTO_BANCARIO = PB.ID_PRODUCTO_BANCARIO
     LEFT OUTER JOIN TARJETA_CREDITO TC
        ON TC.ID_PRODUCTO_BANCARIO = PB.ID_PRODUCTO_BANCARIO
     LEFT OUTER JOIN PRESTAMO P
        ON P.ID_PRODUCTO_BANCARIO = PB.ID_PRODUCTO_BANCARIO
     LEFT OUTER JOIN AVAL A
        ON A.ID_PRODUCTO_BANCARIO = PB.ID_PRODUCTO_BANCARIO
WHERE C.ID_CLIENTE = CPB.ID_CLIENTE
  AND PB.ID_PRODUCTO_BANCARIO = CPB.ID_PRODUCTO_BANCARIO
  AND CAT.ID_CATALOGO = PB.ID_CATALOGO
  AND S.ID_SUCURSAL = PB.ID_SUCURSAL
ORDER BY C.ID_CLIENTE, PB.ID_CATALOGO;
--
-- Consulta de las CUENTAS CORRIENTES de los clientes.
--
SELECT C.NOMBRE_CLIENTE, C.APELLIDOS_CLIENTE,
       CONCAT(D.TIPO_VIA, " ", D.NOMBRE_VIA, ", ", D.NUMERO) AS "DIRECCIÓN",
       CAT.NOMBRE_PRODUCTO, PB.FEC_APERTURA, 
       S.COD_SUCURSAL, S.NOMBRE_SUCURSAL AS "N.SUC.", 
       PB.ID_PRODUCTO_BANCARIO AS "ID_PB",
       CC.ID_CUENTA_CORRIENTE AS "ID_CC", CC.IBAN,
	   CC.IMP_SALDO_ACTUAL
FROM CLIENTE C, CLIENTE_PRODUCTO_BANCARIO CPB,
     DIRECCION D,
     CATALOGO CAT,
     SUCURSAL S,
     PRODUCTO_BANCARIO PB
     LEFT OUTER JOIN CUENTA_CORRIENTE CC
        ON CC.ID_PRODUCTO_BANCARIO = PB.ID_PRODUCTO_BANCARIO
WHERE C.ID_CLIENTE = CPB.ID_CLIENTE
  AND D.ID_DIRECCION = C.ID_DIRECCION
  AND PB.ID_PRODUCTO_BANCARIO = CPB.ID_PRODUCTO_BANCARIO
  AND CAT.ID_CATALOGO = PB.ID_CATALOGO
  AND CAT.COD_PRODUCTO = 'CCC'
  AND S.ID_SUCURSAL = PB.ID_SUCURSAL
ORDER BY C.ID_CLIENTE, PB.ID_CATALOGO;
--
-- Consulta de las TARJETAS DE CREDITO de los clientes.
--
SELECT C.NOMBRE_CLIENTE, C.APELLIDOS_CLIENTE, 
       CAT.NOMBRE_PRODUCTO, PB.FEC_APERTURA, 
       S.COD_SUCURSAL, S.NOMBRE_SUCURSAL AS "N.SUC.", 
       PB.ID_PRODUCTO_BANCARIO AS "ID_PB",
       TC.NUMERO_TARJETA, TC.IMP_LIMITE_TARJETA, 
       TC.IMP_SALDO_PENDIENTE, TC.FORMA_PAGO
FROM CLIENTE C, CLIENTE_PRODUCTO_BANCARIO CPB,
     CATALOGO CAT,
     SUCURSAL S,
     PRODUCTO_BANCARIO PB
     LEFT OUTER JOIN TARJETA_CREDITO TC
        ON TC.ID_PRODUCTO_BANCARIO = PB.ID_PRODUCTO_BANCARIO
WHERE C.ID_CLIENTE = CPB.ID_CLIENTE
  AND PB.ID_PRODUCTO_BANCARIO = CPB.ID_PRODUCTO_BANCARIO
  AND CAT.ID_CATALOGO = PB.ID_CATALOGO
  AND CAT.COD_PRODUCTO = 'TJC'
  AND S.ID_SUCURSAL = PB.ID_SUCURSAL
ORDER BY C.ID_CLIENTE, PB.ID_CATALOGO;
--
-- Consulta de los PRÉSTAMOS de los clientes.
--
SELECT C.NOMBRE_CLIENTE, C.APELLIDOS_CLIENTE, 
       CAT.NOMBRE_PRODUCTO, PB.FEC_APERTURA, 
       S.COD_SUCURSAL, S.NOMBRE_SUCURSAL AS "N.SUC.", 
       PB.ID_PRODUCTO_BANCARIO AS "ID_PB",
       P.NUMERO_PRESTAMO, P.FEC_VENCIMIENTO, P.IMP_CONCEDIDO, P.IMP_SALDO_PENDIENTE 
FROM CLIENTE C, CLIENTE_PRODUCTO_BANCARIO CPB,
     CATALOGO CAT,
     SUCURSAL S,
     PRODUCTO_BANCARIO PB
     LEFT OUTER JOIN PRESTAMO P
        ON P.ID_PRODUCTO_BANCARIO = PB.ID_PRODUCTO_BANCARIO
WHERE C.ID_CLIENTE = CPB.ID_CLIENTE
  AND PB.ID_PRODUCTO_BANCARIO = CPB.ID_PRODUCTO_BANCARIO
  AND CAT.ID_CATALOGO = PB.ID_CATALOGO
  AND CAT.COD_PRODUCTO = 'PTM'
  AND S.ID_SUCURSAL = PB.ID_SUCURSAL
ORDER BY C.ID_CLIENTE, PB.ID_CATALOGO;
--
-- Consulta de los AVALES de los clientes.
--
SELECT C.NOMBRE_CLIENTE, C.APELLIDOS_CLIENTE, 
       CAT.NOMBRE_PRODUCTO, PB.FEC_APERTURA, 
       S.COD_SUCURSAL, S.NOMBRE_SUCURSAL AS "N.SUC.", 
       PB.ID_PRODUCTO_BANCARIO AS "ID_PB",
       A.ID_AVAL, A.NUMERO_AVAL, A.FEC_VENCIMIENTO, A.IMP_AVALADO
FROM CLIENTE C, CLIENTE_PRODUCTO_BANCARIO CPB,
     CATALOGO CAT,
     SUCURSAL S,
     PRODUCTO_BANCARIO PB
     LEFT OUTER JOIN AVAL A
        ON A.ID_PRODUCTO_BANCARIO = PB.ID_PRODUCTO_BANCARIO
WHERE C.ID_CLIENTE = CPB.ID_CLIENTE
  AND PB.ID_PRODUCTO_BANCARIO = CPB.ID_PRODUCTO_BANCARIO
  AND CAT.ID_CATALOGO = PB.ID_CATALOGO
  AND CAT.COD_PRODUCTO = 'AVL'
  AND S.ID_SUCURSAL = PB.ID_SUCURSAL
ORDER BY C.ID_CLIENTE, PB.ID_CATALOGO;
--
-- Actualizar saldos de TARJETA DE CREDITO
--
UPDATE TARJETA_CREDITO T
SET IMP_SALDO_PENDIENTE = (SELECT SUM(M.IMP_MOVIMIENTO) 
                           FROM MOVIMIENTO M
                           WHERE M.ID_PRODUCTO_BANCARIO = T.ID_PRODUCTO_BANCARIO);
--
-- Actualizar saldos de CUENTA CORRIENTE
--                                               
UPDATE CUENTA_CORRIENTE C
SET C.IMP_SALDO_ACTUAL = (SELECT SUM(M.IMP_MOVIMIENTO) 
                          FROM MOVIMIENTO M
                          WHERE M.ID_PRODUCTO_BANCARIO = C.ID_PRODUCTO_BANCARIO);
--
-- Borrar una CUENTA CORRIENTE por el ID de PRODUCTO BANCARIO
--
DELETE FROM CLIENTE_PRODUCTO_BANCARIO
WHERE ID_PRODUCTO_BANCARIO = 11;
DELETE FROM MOVIMIENTO
WHERE ID_PRODUCTO_BANCARIO = 11;
DELETE FROM CUENTA_CORRIENTE
WHERE ID_PRODUCTO_BANCARIO = 11;
DELETE FROM PRODUCTO_BANCARIO
WHERE ID_PRODUCTO_BANCARIO = 11;